const clubRows: [string, string, string][] = [
  ["1. FC Heidenheim 1846", "Bundesliga", ""],
  ["1. FC Kaiserslautern", "2. Bundesliga", ""],
  ["1. FC Köln", "Bundesliga", ""],
  ["1. FC Magdeburg", "2. Bundesliga", ""],
  ["1. FC Nürnberg", "2. Bundesliga", ""],
  ["1. FC Saarbrücken", "3. Liga", ""],
  ["1. FC Schweinfurt 05", "3. Liga", ""],
  ["1. FC Union Berlin", "Bundesliga", ""],
  ["1. FSV Mainz 05", "Bundesliga", ""],
  ["Aarhus Gymnastikforening", "Superliga", ""],
  ["Aberdeen", "Premiership", ""],
  ["AC Milan", "Serie A", ""],
  ["Academia Puerto Cabello", "Primera Division", ""],
  ["Accrington Stanley", "League Two", ""],
  ["AD Ceuta FC", "La Liga 2", ""],
  ["Adelaide United", "A-League Men", ""],
  ["AEK Athens", "Super League", ""],
  ["AFC Bournemouth", "Premier League", ""],
  ["AFC Wimbledon", "League One", ""],
  ["AIK", "Allsvenskan", ""],
  ["AJ Auxerre", "Ligue 1", ""],
  ["Ajax", "Eredivisie", ""],
  ["Al Ahli SFC", "Pro League", ""],
  ["Al Ain", "Pro League", ""],
  ["Al Akhdoud Saudi Club", "Pro League", ""],
  ["Al Ettifaq", "Pro League", ""],
  ["Al Fateh", "Pro League", ""],
  ["Al Fayha", "Pro League", ""],
  ["Al Hazem FC", "Pro League", ""],
  ["Al Hilal", "Pro League", ""],
  ["Al Ittihad", "Pro League", ""],
  ["Al Khaleej", "Pro League", ""],
  ["Al Kholood", "Pro League", ""],
  ["Al Nassr", "Pro League", ""],
  ["Al Qadsiah FC", "Pro League", ""],
  ["Al Riyadh", "Pro League", ""],
  ["Al Shabab", "Pro League", ""],
  ["Al Taawoun FC", "Pro League", ""],
  ["Al-Najma SC", "Pro League", ""],
  ["Alanyaspor", "Süper Lig", ""],
  ["Albacete Balompié", "La Liga 2", ""],
  ["Alemannia Aachen", "3. Liga", ""],
  ["Alianza Lima", "Liga 1", ""],
  ["Alverca", "Primeira Liga", ""],
  ["América de Cali", "Categoría Primera A", ""],
  ["Amiens SC", "Ligue 2", ""],
  ["Angers SCO", "Ligue 1", ""],
  ["Antalyaspor", "Süper Lig", ""],
  ["APOEL FC", "1. Division", ""],
  ["Argentinos Juniors", "Liga Profesional de Fútbol", ""],
  ["Arka Gdynia", "Ekstraklasa", ""],
  ["Arsenal", "Premier League", ""],
  ["AS Monaco", "Ligue 1", ""],
  ["AS Nancy Lorraine", "Ligue 2", ""],
  ["AS Saint-Étienne", "Ligue 2", ""],
  ["Asociația Clubul Sportiv Petrolul 52", "Liga I", ""],
  ["Aston Villa", "Premier League", ""],
  ["Atalanta", "Serie A", ""],
  ["Athletic Club", "La Liga", ""],
  ["Atlanta United", "Major League Soccer", ""],
  ["Atlético Bucaramanga", "Categoría Primera A", ""],
  ["Atlético Grau", "Liga 1", ""],
  ["Atlético Madrid", "La Liga", ""],
  ["Atlético Mineiro", "Série A", ""],
  ["Atlético Nacional", "Categoría Primera A", ""],
  ["Atlético Tucumán", "Liga Profesional de Fútbol", ""],
  ["Auckland FC", "A-League Men", ""],
  ["Austin FC", "Major League Soccer", ""],
  ["Avellino", "Serie B", ""],
  ["AVS Futebol SAD", "Primeira Liga", ""],
  ["AZ Alkmaar", "Eredivisie", ""],
  ["Bahia", "Série A", ""],
  ["Barcelona de Guayaquil", "Serie A", ""],
  ["Barnet", "League Two", ""],
  ["Barnsley", "League One", ""],
  ["Barracas Central", "Liga Profesional de Fútbol", ""],
  ["Barrow", "League Two", ""],
  ["Bayer 04 Leverkusen", "Bundesliga", ""],
  ["Beijing Guoan", "Super League", ""],
  ["Belgrano de Córdoba", "Liga Profesional de Fútbol", ""],
  ["Bengaluru FC", "Super League", ""],
  ["Beşiktaş JK", "Süper Lig", ""],
  ["Birmingham City", "Championship", ""],
  ["BK Häcken", "Allsvenskan", ""],
  ["Blackburn Rovers", "Championship", ""],
  ["Blackpool FC", "League One", ""],
  ["Blau-Weiß Linz", "Bundesliga", ""],
  ["Boca Juniors", "Liga Profesional de Fútbol", ""],
  ["Bohemian FC", "Premier Division", ""],
  ["Bolívar", "División de Fútbol Profesional", ""],
  ["Bologna", "Serie A", ""],
  ["Bolton Wanderers", "League One", ""],
  ["Borussia Dortmund", "Bundesliga", ""],
  ["Borussia Mönchengladbach", "Bundesliga", ""],
  ["Boston River", "Primera División", ""],
  ["Botafogo", "Série A", ""],
  ["Bradford City", "League One", ""],
  ["Brentford", "Premier League", ""],
  ["Brighton & Hove Albion", "Premier League", ""],
  ["Brisbane Roar", "A-League Men", ""],
  ["Bristol City", "Championship", ""],
  ["Bristol Rovers", "League Two", ""],
  ["Bromley", "League Two", ""],
  ["Brøndby IF", "Superliga", ""],
  ["Bruk-Bet Termalica Nieciecza", "Ekstraklasa", ""],
  ["Bryne FK", "Eliteserien", ""],
  ["BSC Young Boys", "Super League", ""],
  ["Burgos CF", "La Liga 2", ""],
  ["Burnley", "Premier League", ""],
  ["Burton Albion", "League One", ""],
  ["CA Aldosivi", "Liga Profesional de Fútbol", ""],
  ["CA Banfield", "Liga Profesional de Fútbol", ""],
  ["CA Osasuna", "La Liga", ""],
  ["Cádiz CF", "La Liga 2", ""],
  ["Cagliari", "Serie A", ""],
  ["Cambridge United", "League Two", ""],
  ["Carabobo FC", "Primera Division", ""],
  ["Caracas FC", "Primera Division", ""],
  ["Cardiff City", "League One", ""],
  ["Carrarese", "Serie B", ""],
  ["Casa Pia", "Primeira Liga", ""],
  ["Catanzaro", "Serie B", ""],
  ["Çaykur Rizespor", "Süper Lig", ""],
  ["CD Castellón", "La Liga 2", ""],
  ["CD Leganés", "La Liga 2", ""],
  ["CD Mirandés", "La Liga 2", ""],
  ["CD Nacional", "Primeira Liga", ""],
  ["CD Palestino", "Primera Division", ""],
  ["CD Tondela", "Primeira Liga", ""],
  ["Celtic", "Premiership", ""],
  ["Central Coast Mariners", "A-League Men", ""],
  ["Central Cordoba SdE", "Liga Profesional de Fútbol", ""],
  ["Cercle Brugge KSV", "Pro League", ""],
  ["Cerro Largo", "Primera División", ""],
  ["Cerro Porteño", "División Profesional", ""],
  ["Cesena FC", "Serie B", ""],
  ["CF Montréal", "Major League Soccer", ""],
  ["CFR Cluj", "Liga I", ""],
  ["Changchun Yatai", "Super League", ""],
  ["Charlotte FC", "Major League Soccer", ""],
  ["Charlton Athletic", "Championship", ""],
  ["Chelsea", "Premier League", ""],
  ["Cheltenham Town", "League Two", ""],
  ["Chengdu Rongcheng", "Super League", ""],
  ["Chennaiyin FC", "Super League", ""],
  ["Chesterfield", "League Two", ""],
  ["Chicago Fire", "Major League Soccer", ""],
  ["Cienciano", "Liga 1", ""],
  ["Clermont Foot 63", "Ligue 2", ""],
  ["Club Atlético San Martín", "Liga Profesional de Fútbol", ""],
  ["Club Atlético Sarmiento", "Liga Profesional de Fútbol", ""],
  ["Club Atlético Unión", "Liga Profesional de Fútbol", ""],
  ["Club Brugge KV", "Pro League", ""],
  ["Club Nacional de Football", "Primera División", ""],
  ["Club Olimpia", "División Profesional", ""],
  ["Colchester United", "League Two", ""],
  ["Colo-Colo", "Primera Division", ""],
  ["Colorado Rapids", "Major League Soccer", ""],
  ["Columbus Crew", "Major League Soccer", ""],
  ["Como", "Serie A", ""],
  ["Córdoba CF", "La Liga 2", ""],
  ["Corinthians", "Série A", ""],
  ["Cork City", "Premier Division", ""],
  ["Coventry City", "Championship", ""],
  ["Cracovia", "Ekstraklasa", ""],
  ["Crawley Town", "League Two", ""],
  ["Cremonese", "Serie A", ""],
  ["Crewe Alexandra", "League Two", ""],
  ["Cruzeiro", "Série A", ""],
  ["Crystal Palace", "Premier League", ""],
  ["Csíkszereda Miercurea Ciuc", "Liga I", ""],
  ["Cultural Leonesa", "La Liga 2", ""],
  ["Daegu FC", "K League 1", ""],
  ["Daejeon Citizen", "K League 1", ""],
  ["Dalian Yingbo", "Super League", ""],
  ["Damac FC", "Pro League", ""],
  ["DC United", "Major League Soccer", ""],
  ["Defensa y Justicia", "Liga Profesional de Fútbol", ""],
  ["Degerfors IF", "Allsvenskan", ""],
  ["Deportes Iquique", "Primera Division", ""],
  ["Deportivo Alavés", "La Liga", ""],
  ["Deportivo Riestra", "Liga Profesional de Fútbol", ""],
  ["Deportivo Táchira", "Primera Division", ""],
  ["Derby County", "Championship", ""],
  ["Derry City", "Premier Division", ""],
  ["Dinamo Bucureşti", "Liga I", ""],
  ["Dinamo Zagreb", "Hrvatska nogometna liga", ""],
  ["Djurgårdens IF", "Allsvenskan", ""],
  ["Doncaster Rovers", "League One", ""],
  ["Drogheda United", "Premier Division", ""],
  ["DSC Arminia Bielefeld", "2. Bundesliga", ""],
  ["Dundee FC", "Premiership", ""],
  ["Dundee United FC", "Premiership", ""],
  ["Dynamo Dresden", "2. Bundesliga", ""],
  ["Dynamo Kyiv", "Premier League", ""],
  ["East Bengal FC", "Super League", ""],
  ["Eintracht Braunschweig", "2. Bundesliga", ""],
  ["Eintracht Frankfurt", "Bundesliga", ""],
  ["Elche CF", "La Liga", ""],
  ["Empoli", "Serie B", ""],
  ["En Avant Guingamp", "Ligue 2", ""],
  ["ESTAC Troyes", "Ligue 2", ""],
  ["Estrela da Amadora", "Primeira Liga", ""],
  ["Estudiantes de La Plata", "Liga Profesional de Fútbol", ""],
  ["Everton", "Premier League", ""],
  ["Excelsior", "Eredivisie", ""],
  ["Exeter City", "League One", ""],
  ["Eyüpspor", "Süper Lig", ""],
  ["Falkirk", "Premiership", ""],
  ["Famalicão", "Primeira Liga", ""],
  ["Fatih Karagümrük", "Süper Lig", ""],
  ["FBC Melgar", "Liga 1", ""],
  ["FC Andorra", "La Liga 2", ""],
  ["FC Annecy", "Ligue 2", ""],
  ["FC Anyang", "K League 1", ""],
  ["FC Argeș", "Liga I", ""],
  ["FC Arouca", "Primeira Liga", ""],
  ["FC Augsburg", "Bundesliga", ""],
  ["FC Barcelona", "La Liga", ""],
  ["FC Basel 1893", "Super League", ""],
  ["FC Bayern München", "Bundesliga", ""],
  ["FC Botoşani", "Liga I", ""],
  ["FC Cincinnati", "Major League Soccer", ""],
  ["FC Dallas", "Major League Soccer", ""],
  ["FC Energie Cottbus", "3. Liga", ""],
  ["FC Erzgebirge Aue", "3. Liga", ""],
  ["FC Goa", "Super League", ""],
  ["FC Groningen", "Eredivisie", ""],
  ["FC Hansa Rostock", "3. Liga", ""],
  ["FC Hermannstadt", "Liga I", ""],
  ["FC Ingolstadt 04", "3. Liga", ""],
  ["FC København", "Superliga", ""],
  ["FC Lausanne-Sport", "Super League", ""],
  ["FC Lorient", "Ligue 1", ""],
  ["FC Lugano", "Super League", ""],
  ["FC Luzern", "Super League", ""],
  ["FC Metz", "Ligue 1", ""],
  ["FC Midtjylland", "Superliga", ""],
  ["FC Nantes", "Ligue 1", ""],
  ["FC Nordsjælland", "Superliga", ""],
  ["FC Porto", "Primeira Liga", ""],
  ["FC Red Bull Salzburg", "Bundesliga", ""],
  ["FC Schalke 04", "2. Bundesliga", ""],
  ["FC Seoul", "K League 1", ""],
  ["FC Sion", "Super League", ""],
  ["FC St. Pauli", "Bundesliga", ""],
  ["FC St.Gallen 1879", "Super League", ""],
  ["FC Thun", "Super League", ""],
  ["FC Twente", "Eredivisie", ""],
  ["FC Utrecht", "Eredivisie", ""],
  ["FC Volendam", "Eredivisie", ""],
  ["FC Winterthur", "Super League", ""],
  ["FC Zürich", "Super League", ""],
  ["FCSB", "Liga I", ""],
  ["FCV Dender EH", "Pro League", ""],
  ["FCV Farul Constanța", "Liga I", ""],
  ["Fenerbahçe SK", "Süper Lig", ""],
  ["Ferencvárosi Torna Club", "Nemzeti Bajnokság I", ""],
  ["Feyenoord", "Eredivisie", ""],
  ["Fiorentina", "Serie A", ""],
  ["FK Austria Wien", "Bundesliga", ""],
  ["FK Bodø/Glimt", "Eliteserien", ""],
  ["FK Haugesund", "Eliteserien", ""],
  ["Flamengo", "Série A", ""],
  ["Fleetwood Town", "League Two", ""],
  ["Fluminense", "Série A", ""],
  ["Fortaleza", "Série A", ""],
  ["Fortuna Düsseldorf", "2. Bundesliga", ""],
  ["Fortuna Sittard", "Eredivisie", ""],
  ["Fredericia", "Superliga", ""],
  ["Fredrikstad FK", "Eliteserien", ""],
  ["Frosinone", "Serie B", ""],
  ["Fulham FC", "Premier League", ""],
  ["GAIS", "Allsvenskan", ""],
  ["Galatasaray SK", "Süper Lig", ""],
  ["Galway United", "Premier Division", ""],
  ["Gangwon FC", "K League 1", ""],
  ["Gaziantep FK", "Süper Lig", ""],
  ["GD Estoril Praia", "Primeira Liga", ""],
  ["Gençlerbirliği SK", "Süper Lig", ""],
  ["Genoa", "Serie A", ""],
  ["Getafe CF", "La Liga", ""],
  ["Gil Vicente FC", "Primeira Liga", ""],
  ["Gillingham", "League Two", ""],
  ["Gimcheon Sangmu FC", "K League 1", ""],
  ["Gimnasia y Esgrima La Plata", "Liga Profesional de Fútbol", ""],
  ["Girona FC", "La Liga", ""],
  ["GKS Katowice", "Ekstraklasa", ""],
  ["Go Ahead Eagles", "Eredivisie", ""],
  ["Godoy Cruz", "Liga Profesional de Fútbol", ""],
  ["Górnik Zabrze", "Ekstraklasa", ""],
  ["Göztepe SK", "Süper Lig", ""],
  ["Granada CF", "La Liga 2", ""],
  ["Grasshopper Club Zürich", "Super League", ""],
  ["Grazer AK 1902", "Bundesliga", ""],
  ["Grêmio", "Série A", ""],
  ["Grenoble Foot 38", "Ligue 2", ""],
  ["Grimsby Town", "League Two", ""],
  ["Gualberto Villarroel SJ", "División de Fútbol Profesional", ""],
  ["Guaraní", "División Profesional", ""],
  ["Gwangju FC", "K League 1", ""],
  ["Hajduk Split", "Hrvatska nogometna liga", ""],
  ["Halmstads BK", "Allsvenskan", ""],
  ["Hamarkameratene", "Eliteserien", ""],
  ["Hamburger SV", "Bundesliga", ""],
  ["Hammarby Fotboll", "Allsvenskan", ""],
  ["Hannover 96", "2. Bundesliga", ""],
  ["Harrogate Town", "League Two", ""],
  ["Hearts", "Premiership", ""],
  ["Hellas Verona FC", "Serie A", ""],
  ["Henan FC", "Super League", ""],
  ["Heracles Almelo", "Eredivisie", ""],
  ["Hertha BSC", "2. Bundesliga", ""],
  ["Hibernian", "Premiership", ""],
  ["HJK Helsinki", "Veikkausliiga", ""],
  ["Holstein Kiel", "2. Bundesliga", ""],
  ["Houston Dynamo", "Major League Soccer", ""],
  ["Huddersfield Town", "League One", ""],
  ["Hull City", "Championship", ""],
  ["Huracán", "Liga Profesional de Fútbol", ""],
  ["Hyderabad FC", "Super League", ""],
  ["IF Brommapojkarna", "Allsvenskan", ""],
  ["IF Elfsborg", "Allsvenskan", ""],
  ["IFK Göteborg", "Allsvenskan", ""],
  ["IFK Norrköping", "Allsvenskan", ""],
  ["IFK Värnamo", "Allsvenskan", ""],
  ["IK Sirius", "Allsvenskan", ""],
  ["Independiente", "Liga Profesional de Fútbol", ""],
  ["Independiente del Valle", "Serie A", ""],
  ["Independiente Rivadavia", "Liga Profesional de Fútbol", ""],
  ["Instituto Atlético Central Córdoba", "Liga Profesional de Fútbol", ""],
  ["Inter", "Serie A", ""],
  ["Inter Miami", "Major League Soccer", ""],
  ["Internacional", "Série A", ""],
  ["Ipswich Town", "Championship", ""],
  ["Jagiellonia Białystok", "Ekstraklasa", ""],
  ["Jamshedpur FC", "Super League", ""],
  ["Jeju United FC", "K League 1", ""],
  ["Jeonbuk Hyundai Motors", "K League 1", ""],
  ["Juventus", "Serie A", ""],
  ["KAA Gent", "Pro League", ""],
  ["Karlsruher SC", "2. Bundesliga", ""],
  ["Kasımpaşa SK", "Süper Lig", ""],
  ["Kayserispor", "Süper Lig", ""],
  ["Kerala Blasters FC", "Super League", ""],
  ["KFUM-Kameratene Oslo", "Eliteserien", ""],
  ["Kilmarnock", "Premiership", ""],
  ["Kocaelispor", "Süper Lig", ""],
  ["Konyaspor", "Süper Lig", ""],
  ["Korona Kielce", "Ekstraklasa", ""],
  ["KRC Genk", "Pro League", ""],
  ["Kristiansund BK", "Eliteserien", ""],
  ["KV Mechelen", "Pro League", ""],
  ["KVC Westerlo", "Pro League", ""],
  ["LA Galaxy", "Major League Soccer", ""],
  ["Lanús", "Liga Profesional de Fútbol", ""],
  ["LASK Linz", "Bundesliga", ""],
  ["Lazio", "Serie A", ""],
  ["LDU Quito", "Serie A", ""],
  ["Le Havre AC", "Ligue 1", ""],
  ["Le Mans FC", "Ligue 2", ""],
  ["Lecce", "Serie A", ""],
  ["Lech Poznań", "Ekstraklasa", ""],
  ["Lechia Gdańsk", "Ekstraklasa", ""],
  ["Leeds United", "Premier League", ""],
  ["Legia Warszawa", "Ekstraklasa", ""],
  ["Leicester City", "Championship", ""],
  ["Levante UD", "La Liga", ""],
  ["Leyton Orient", "League One", ""],
  ["Libertad", "División Profesional", ""],
  ["Lille OSC", "Ligue 1", ""],
  ["Lincoln City", "League One", ""],
  ["Liverpool", "Premier League", ""],
  ["Livingston FC", "Premiership", ""],
  ["Los Angeles FC", "Major League Soccer", ""],
  ["Luton Town", "League One", ""],
  ["Macarthur FC", "A-League Men", ""],
  ["Málaga CF", "La Liga 2", ""],
  ["Malmö FF", "Allsvenskan", ""],
  ["Manchester City", "Premier League", ""],
  ["Manchester United", "Premier League", ""],
  ["Mansfield Town", "League One", ""],
  ["Mantova", "Serie B", ""],
  ["Medipol Başakşehir FK", "Süper Lig", ""],
  ["Meizhou Hakka", "Super League", ""],
  ["Melbourne City FC", "A-League Men", ""],
  ["Melbourne Victory", "A-League Men", ""],
  ["Metaloglobus București", "Liga I", ""],
  ["Middlesbrough", "Championship", ""],
  ["Millwall FC", "Championship", ""],
  ["Milton Keynes Dons", "League Two", ""],
  ["Minnesota United FC", "Major League Soccer", ""],
  ["Mjällby AIF", "Allsvenskan", ""],
  ["Modena", "Serie B", ""],
  ["Mohammedan SC", "Super League", ""],
  ["Mohun Bagan Super Giant", "Super League", ""],
  ["Molde FK", "Eliteserien", ""],
  ["Montpellier HSC", "Ligue 2", ""],
  ["Monza", "Serie B", ""],
  ["Moreirense FC", "Primeira Liga", ""],
  ["Motherwell FC", "Premiership", ""],
  ["Motor Lublin", "Ekstraklasa", ""],
  ["MSV Duisburg", "3. Liga", ""],
  ["Mumbai City FC", "Super League", ""],
  ["Mushuc Runa", "Serie A", ""],
  ["NAC Breda", "Eredivisie", ""],
  ["Nacional Potosí", "División de Fútbol Profesional", ""],
  ["Napoli", "Serie A", ""],
  ["Nashville SC", "Major League Soccer", ""],
  ["NEC Nijmegen", "Eredivisie", ""],
  ["NEOM SC", "Pro League", ""],
  ["New England Revolution", "Major League Soccer", ""],
  ["New York City FC", "Major League Soccer", ""],
  ["New York Red Bulls", "Major League Soccer", ""],
  ["Newcastle Jets", "A-League Men", ""],
  ["Newcastle United", "Premier League", ""],
  ["Newell's Old Boys", "Liga Profesional de Fútbol", ""],
  ["Newport County", "League Two", ""],
  ["Northampton Town", "League One", ""],
  ["NorthEast United", "Super League", ""],
  ["Norwich City", "Championship", ""],
  ["Nottingham Forest", "Premier League", ""],
  ["Notts County", "League Two", ""],
  ["Odense Boldklub", "Superliga", ""],
  ["Odisha FC", "Super League", ""],
  ["OGC Nice", "Ligue 1", ""],
  ["Oldham Athletic", "League Two", ""],
  ["Olympiacos FC", "Super League", ""],
  ["Olympique de Marseille", "Ligue 1", ""],
  ["Olympique Lyonnais", "Ligue 1", ""],
  ["Once Caldas", "Categoría Primera A", ""],
  ["Orlando City SC", "Major League Soccer", ""],
  ["Östers IF", "Allsvenskan", ""],
  ["Oțelul Galați", "Liga I", ""],
  ["Oud-Heverlee Leuven", "Pro League", ""],
  ["Oxford United", "Championship", ""],
  ["Padova", "Serie B", ""],
  ["Palermo FC", "Serie B", ""],
  ["Palmeiras", "Série A", ""],
  ["Panathinaikos FC", "Super League", ""],
  ["PAOK", "Super League", ""],
  ["Paris FC", "Ligue 1", ""],
  ["Paris Saint-Germain", "Ligue 1", ""],
  ["Parma", "Serie A", ""],
  ["Pau FC", "Ligue 2", ""],
  ["PEC Zwolle", "Eredivisie", ""],
  ["Peñarol", "Primera División", ""],
  ["Perth Glory", "A-League Men", ""],
  ["Pescara", "Serie B", ""],
  ["Peterborough United", "League One", ""],
  ["Philadelphia Union", "Major League Soccer", ""],
  ["Piast Gliwice", "Ekstraklasa", ""],
  ["Pisa", "Serie A", ""],
  ["Platense", "Liga Profesional de Fútbol", ""],
  ["Plymouth Argyle", "League One", ""],
  ["Pogoń Szczecin", "Ekstraklasa", ""],
  ["Pohang Steelers", "K League 1", ""],
  ["Port Vale", "League One", ""],
  ["Portland Timbers", "Major League Soccer", ""],
  ["Portsmouth", "Championship", ""],
  ["Preston North End", "Championship", ""],
  ["PSV", "Eredivisie", ""],
  ["Punjab FC", "Super League", ""],
  ["Qarabağ FK", "Premyer Liqa", ""],
  ["Qingdao Hainiu FC", "Super League", ""],
  ["Qingdao West Coast FC", "Super League", ""],
  ["Queens Park Rangers", "Championship", ""],
  ["RAAL La Louvière", "Pro League", ""],
  ["Racing Club", "Liga Profesional de Fútbol", ""],
  ["Racing Club de Montevideo", "Primera División", ""],
  ["Racing Santander", "La Liga 2", ""],
  ["Radomiak Radom", "Ekstraklasa", ""],
  ["Raków Częstochowa", "Ekstraklasa", ""],
  ["Randers FC", "Superliga", ""],
  ["Rangers FC", "Premiership", ""],
  ["Rapid Bucuresti", "Liga I", ""],
  ["Rayo Vallecano", "La Liga", ""],
  ["RB Leipzig", "Bundesliga", ""],
  ["RC Celta", "La Liga", ""],
  ["RC Deportivo de La Coruña", "La Liga 2", ""],
  ["RC Lens", "Ligue 1", ""],
  ["RC Strasbourg Alsace", "Ligue 1", ""],
  ["RCD Espanyol", "La Liga", ""],
  ["RCD Mallorca", "La Liga", ""],
  ["Reading FC", "League One", ""],
  ["Real Betis Balompié", "La Liga", ""],
  ["Real Madrid", "La Liga", ""],
  ["Real Oviedo", "La Liga", ""],
  ["Real Salt Lake", "Major League Soccer", ""],
  ["Real Sociedad", "La Liga", ""],
  ["Real Sociedad de Fútbol B", "La Liga 2", ""],
  ["Real Sporting de Gijón", "La Liga 2", ""],
  ["Real Valladolid CF", "La Liga 2", ""],
  ["Real Zaragoza", "La Liga 2", ""],
  ["Red Star FC", "Ligue 2", ""],
  ["Reggiana", "Serie B", ""],
  ["Rio Ave FC", "Primeira Liga", ""],
  ["River Plate", "Liga Profesional de Fútbol", ""],
  ["Rodez Aveyron Football", "Ligue 2", ""],
  ["Roma", "Serie A", ""],
  ["Rosario Central", "Liga Profesional de Fútbol", ""],
  ["Rosenborg BK", "Eliteserien", ""],
  ["Rot-Weiss Essen", "3. Liga", ""],
  ["Rotherham United", "League One", ""],
  ["Royal Antwerp FC", "Pro League", ""],
  ["Royal Charleroi Sporting Club", "Pro League", ""],
  ["RSC Anderlecht", "Pro League", ""],
  ["Salford City", "League Two", ""],
  ["Sampdoria", "Serie B", ""],
  ["Samsunspor", "Süper Lig", ""],
  ["San Antonio Bulo Bulo", "División de Fútbol Profesional", ""],
  ["San Diego FC", "Major League Soccer", ""],
  ["San Jose Earthquakes", "Major League Soccer", ""],
  ["San Lorenzo de Almagro", "Liga Profesional de Fútbol", ""],
  ["Sandefjord Fotball", "Eliteserien", ""],
  ["Santa Clara", "Primeira Liga", ""],
  ["São Paulo", "Série A", ""],
  ["Sarpsborg 08 FF", "Eliteserien", ""],
  ["Sassuolo", "Serie A", ""],
  ["SC Freiburg", "Bundesliga", ""],
  ["SC Heerenveen", "Eredivisie", ""],
  ["SC Paderborn 07", "2. Bundesliga", ""],
  ["SC Preußen Münster", "2. Bundesliga", ""],
  ["SC Rheindorf Altach", "Bundesliga", ""],
  ["SC Verl", "3. Liga", ""],
  ["SD Eibar", "La Liga 2", ""],
  ["SD Huesca", "La Liga 2", ""],
  ["Seattle Sounders FC", "Major League Soccer", ""],
  ["Servette FC", "Super League", ""],
  ["Sevilla FC", "La Liga", ""],
  ["Shakhtar Donetsk", "Premier League", ""],
  ["Shamrock Rovers", "Premier Division", ""],
  ["Shandong Taishan", "Super League", ""],
  ["Shanghai Port", "Super League", ""],
  ["Shanghai Shenhua", "Super League", ""],
  ["Sheffield United", "Championship", ""],
  ["Sheffield Wednesday", "Championship", ""],
  ["Shelbourne FC", "Premier Division", ""],
  ["Shenzhen Peng City", "Super League", ""],
  ["Shrewsbury Town", "League Two", ""],
  ["Silkeborg IF", "Superliga", ""],
  ["Sint-Truidense VV", "Pro League", ""],
  ["SK Brann", "Eliteserien", ""],
  ["SK Rapid", "Bundesliga", ""],
  ["SK Slavia Praha", "První liga", ""],
  ["SK Sturm Graz", "Bundesliga", ""],
  ["SL Benfica", "Primeira Liga", ""],
  ["Sligo Rovers", "Premier Division", ""],
  ["Sønderjyske Fodbold", "Superliga", ""],
  ["Southampton", "Championship", ""],
  ["Sparta Praha", "První liga", ""],
  ["Sparta Rotterdam", "Eredivisie", ""],
  ["Spezia", "Serie B", ""],
  ["Sporting Club Bastia", "Ligue 2", ""],
  ["Sporting Clube de Braga", "Primeira Liga", ""],
  ["Sporting CP", "Primeira Liga", ""],
  ["Sporting Cristal", "Liga 1", ""],
  ["Sporting Kansas City", "Major League Soccer", ""],
  ["Sportivo Luqueño", "División Profesional", ""],
  ["SpVgg Greuther Fürth", "2. Bundesliga", ""],
  ["SS Juve Stabia", "Serie B", ""],
  ["SSC Bari", "Serie B", ""],
  ["SSV Jahn Regensburg", "3. Liga", ""],
  ["SSV Ulm 1846", "3. Liga", ""],
  ["St Patrick's Athletic FC", "Premier Division", ""],
  ["St. Louis CITY SC", "Major League Soccer", ""],
  ["St. Mirren", "Premiership", ""],
  ["Stade Brestois 29", "Ligue 1", ""],
  ["Stade de Reims", "Ligue 2", ""],
  ["Stade Lavallois Mayenne FC", "Ligue 2", ""],
  ["Stade Rennais FC", "Ligue 1", ""],
  ["Standard de Liège", "Pro League", ""],
  ["Stevenage", "League One", ""],
  ["Stockport County", "League One", ""],
  ["Stoke City", "Championship", ""],
  ["Strømsgodset IF", "Eliteserien", ""],
  ["Südtirol", "Serie B", ""],
  ["Sunderland", "Premier League", ""],
  ["Suwon FC", "K League 1", ""],
  ["SV Darmstadt 98", "2. Bundesliga", ""],
  ["SV Elversberg", "2. Bundesliga", ""],
  ["SV Ried", "Bundesliga", ""],
  ["SV Waldhof Mannheim", "3. Liga", ""],
  ["SV Wehen Wiesbaden", "3. Liga", ""],
  ["SV Werder Bremen", "Bundesliga", ""],
  ["SV Zulte Waregem", "Pro League", ""],
  ["Swansea City", "Championship", ""],
  ["Swindon Town", "League Two", ""],
  ["Sydney FC", "A-League Men", ""],
  ["Talleres", "Liga Profesional de Fútbol", ""],
  ["Telstar", "Eredivisie", ""],
  ["Tianjin Jinmen Tiger", "Super League", ""],
  ["Tigre", "Liga Profesional de Fútbol", ""],
  ["Torino", "Serie A", ""],
  ["Toronto FC", "Major League Soccer", ""],
  ["Tottenham Hotspur", "Premier League", ""],
  ["Toulouse FC", "Ligue 1", ""],
  ["Trabzonspor", "Süper Lig", ""],
  ["Tranmere Rovers", "League Two", ""],
  ["Tromsø IL", "Eliteserien", ""],
  ["TSG 1899 Hoffenheim", "Bundesliga", ""],
  ["TSG 1899 Hoffenheim II", "3. Liga", ""],
  ["TSV 1860 München", "3. Liga", ""],
  ["TSV Hartberg", "Bundesliga", ""],
  ["TSV Havelse", "3. Liga", ""],
  ["UD Almería", "La Liga 2", ""],
  ["UD Las Palmas", "La Liga 2", ""],
  ["Udinese", "Serie A", ""],
  ["Ulsan HD FC", "K League 1", ""],
  ["Unión Española", "Primera Division", ""],
  ["Union Saint-Gilloise", "Pro League", ""],
  ["Unirea Slobozia", "Liga I", ""],
  ["United Tigers SC", "Super League", ""],
  ["Universidad Católica", "Primera Division", ""],
  ["Universidad Católica del Ecuador", "Serie A", ""],
  ["Universidad de Chile", "Primera Division", ""],
  ["Universitario de Deportes", "Liga 1", ""],
  ["Universitatea Cluj", "Liga I", ""],
  ["Universitatea Craiova", "Liga I", ""],
  ["US Boulogne Cote d'Opale", "Ligue 2", ""],
  ["USL Dunkerque", "Ligue 2", ""],
  ["UTA Arad", "Liga I", ""],
  ["Valencia CF", "La Liga", ""],
  ["Vålerenga Fotball", "Eliteserien", ""],
  ["Vancouver Whitecaps FC", "Major League Soccer", ""],
  ["Vasco da Gama", "Série A", ""],
  ["Vejle Boldklub", "Superliga", ""],
  ["Vélez Sarsfield", "Liga Profesional de Fútbol", ""],
  ["Venezia", "Serie B", ""],
  ["VfB Stuttgart", "Bundesliga", ""],
  ["VfB Stuttgart II", "3. Liga", ""],
  ["VfL Bochum 1848", "2. Bundesliga", ""],
  ["VfL Osnabrück", "3. Liga", ""],
  ["VfL Wolfsburg", "Bundesliga", ""],
  ["Viborg FF", "Superliga", ""],
  ["Viking FK", "Eliteserien", ""],
  ["Viktoria Köln", "3. Liga", ""],
  ["Viktoria Plzeň", "První liga", ""],
  ["Villarreal CF", "La Liga", ""],
  ["Virtus Entella", "Serie B", ""],
  ["Vitória", "Série A", ""],
  ["Vitória SC", "Primeira Liga", ""],
  ["Walsall", "League Two", ""],
  ["Waterford FC", "Premier Division", ""],
  ["Watford", "Championship", ""],
  ["Wellington Phoenix", "A-League Men", ""],
  ["West Bromwich Albion", "Championship", ""],
  ["West Ham United", "Premier League", ""],
  ["Western Sydney Wanderers", "A-League Men", ""],
  ["Western United", "A-League Men", ""],
  ["Widzew Łódź", "Ekstraklasa", ""],
  ["Wigan Athletic", "League One", ""],
  ["Wisła Płock", "Ekstraklasa", ""],
  ["Wolfsberger AC", "Bundesliga", ""],
  ["Wolverhampton Wanderers", "Premier League", ""],
  ["Wrexham", "Championship", ""],
  ["WSG Tirol", "Bundesliga", ""],
  ["Wuhan Three Towns", "Super League", ""],
  ["Wycombe Wanderers", "League One", ""],
  ["Yunnan Yukun", "Super League", ""],
  ["Zagłębie Lubin", "Ekstraklasa", ""],
  ["Zhejiang FC", "Super League", ""],
];
