export const clubRows: [string, string, string][] = [
  ["FC Heidenheim 1846", "Bundesliga", "Alemanha"],
  ["FC Kaiserslautern", "Bundesliga", "Alemanha"],
  ["FC Köln", "Bundesliga", "Alemanha"],
  ["FC Magdeburg", "Bundesliga", "Alemanha"],
  ["FC Nürnberg", "Bundesliga", "Alemanha"],
  ["FC Saarbrücken", "Liga", "Alemanha"],
  ["FC Schweinfurt 05", "Liga", "Alemanha"],
  ["FC Union Berlin", "Bundesliga", "Alemanha"],
  ["FSV Mainz 05", "Bundesliga", "Alemanha"],
  ["Aarhus Gymnastikforening", "Superliga", "Dinamarca"],
  ["Aberdeen", "Premiership", "Escócia"],
  ["AC Milan", "Serie A", "Itália"],
  ["Academia Puerto Cabello", "Primera Division", "Venezuela"],
  ["Accrington Stanley", "League Two", "Inglaterra"],
  ["AD Ceuta FC", "La Liga 2", "Espanha"],
  ["Adelaide United", "A-League Men", "Austrália"],
  ["AEK Athens", "Super League", "Grécia"],
  ["AFC Bournemouth", "Premier League", "Inglaterra"],
  ["AFC Wimbledon", "League One", "Inglaterra"],
  ["AIK", "Allsvenskan", "Suécia"],
  ["AJ Auxerre", "Ligue 1", "França"],
  ["Ajax", "Eredivisie", "Países Baixos"],
  ["Al Ahli SFC", "Pro League", "Arábia Saudita"],
  ["Al Ain", "Pro League", "Arábia Saudita"],
  ["Al Akhdoud Saudi Club", "Pro League", "Arábia Saudita"],
  ["Al Ettifaq", "Pro League", "Arábia Saudita"],
  ["Al Fateh", "Pro League", "Arábia Saudita"],
  ["Al Fayha", "Pro League", "Arábia Saudita"],
  ["Al Hazem FC", "Pro League", "Arábia Saudita"],
  ["Al Hilal", "Pro League", "Arábia Saudita"],
  ["Al Ittihad", "Pro League", "Arábia Saudita"],
  ["Al Khaleej", "Pro League", "Arábia Saudita"],
  ["Al Kholood", "Pro League", "Arábia Saudita"],
  ["Al Nassr", "Pro League", "Arábia Saudita"],
  ["Al Qadsiah FC", "Pro League", "Arábia Saudita"],
  ["Al Riyadh", "Pro League", "Arábia Saudita"],
  ["Al Shabab", "Pro League", "Arábia Saudita"],
  ["Al Taawoun FC", "Pro League", "Arábia Saudita"],
  ["Al-Najma SC", "Pro League", "Arábia Saudita"],
  ["Alanyaspor", "Süper Lig", "Turquia"],
  ["Albacete Balompié", "La Liga 2", "Espanha"],
  ["Alemannia Aachen", "3. Liga", "Alemanha"],
  ["Alianza Lima", "Liga 1", "Peru"],
  ["Alverca", "Primeira Liga", "Portugal"],
  ["América de Cali", "Categoría Primera A", "Colômbia"],
  ["Amiens SC", "Ligue 2", "França"],
  ["Angers SCO", "Ligue 1", "França"],
  ["Antalyaspor", "Süper Lig", "Turquia"],
  ["APOEL FC", "1. Division", "Chipre"],
  ["Argentinos Juniors", "Liga Profesional de Fútbol", "Argentina"],
  ["Arka Gdynia", "Ekstraklasa", "Polônia"],
  ["Arsenal", "Premier League", "Inglaterra"],
  ["AS Monaco", "Ligue 1", "França"],
  ["AS Nancy Lorraine", "Ligue 2", "França"],
  ["AS Saint-Étienne", "Ligue 2", "França"],
  ["Asociația Clubul Sportiv Petrolul 52", "Liga I", "Roménia"],
  ["Aston Villa", "Premier League", "Inglaterra"],
  ["Atalanta", "Serie A", "Itália"],
  ["Athletic Club", "La Liga", "Espanha"],
  ["Atlanta United", "Major League Soccer", "EUA"],
  ["Atlético Bucaramanga", "Categoría Primera A", "Colômbia"],
  ["Atlético Grau", "Liga 1", "Peru"],
  ["Atlético Madrid", "La Liga", "Espanha"],
  ["Atlético Mineiro", "Série A", "Brasil"],
  ["Atlético Nacional", "Categoría Primera A", "Colômbia"],
  ["Atlético Tucumán", "Liga Profesional de Fútbol", "Argentina"],
  ["Auckland FC", "A-League Men", "Austrália"],
  ["Austin FC", "Major League Soccer", "EUA"],
  ["Avellino", "Serie B", "Itália"],
  ["AVS Futebol SAD", "Primeira Liga", "Portugal"],
  ["AZ Alkmaar", "Eredivisie", "Países Baixos"],
  ["Bahia", "Série A", "Brasil"],
  ["Barcelona de Guayaquil", "Serie A", "Ecuador"],
  ["Barnet", "League Two", "Inglaterra"],
  ["Barnsley", "League One", "Inglaterra"],
  ["Barracas Central", "Liga Profesional de Fútbol", "Argentina"],
  ["Barrow", "League Two", "Inglaterra"],
  ["Bayer 04 Leverkusen", "Bundesliga", "Alemanha"],
  ["Beijing Guoan", "Super League", "Chile"],
  ["Belgrano de Córdoba", "Liga Profesional de Fútbol", "Argentina"],
  ["Bengaluru FC", "Super League", "Índia"],
  ["Beşiktaş JK", "Süper Lig", "Turquia"],
  ["Birmingham City", "Championship", "Inglaterra"],
  ["BK Häcken", "Allsvenskan", "Suécia"],
  ["Blackburn Rovers", "Championship", "Inglaterra"],
  ["Blackpool FC", "League One", "Inglaterra"],
  ["Blau-Weiß Linz", "Bundesliga", "Alemanha"],
  ["Boca Juniors", "Liga Profesional de Fútbol", "Argentina"],
  ["Bohemian FC", "Premier Division", "Irlanda"],
  ["Bolívar", "División de Fútbol Profesional", "Bolívia"],
  ["Bologna", "Serie A", "Itália"],
  ["Bolton Wanderers", "League One", "Inglaterra"],
  ["Borussia Dortmund", "Bundesliga", "Alemanha"],
  ["Borussia Mönchengladbach", "Bundesliga", "Alemanha"],
  ["Boston River", "Primera División", "Uruguai"],
  ["Botafogo", "Série A", "Brasil"],
  ["Bradford City", "League One", "Inglaterra"],
  ["Brentford", "Premier League", "Inglaterra"],
  ["Brighton & Hove Albion", "Premier League", "Inglaterra"],
  ["Brisbane Roar", "A-League Men", "Austrália"],
  ["Bristol City", "Championship", "Inglaterra"],
  ["Bristol Rovers", "League Two", "Inglaterra"],
  ["Bromley", "League Two", "Inglaterra"],
  ["Brøndby IF", "Superliga", "Dinamarca"],
  ["Bruk-Bet Termalica Nieciecza", "Ekstraklasa", "Polônia"],
  ["Bryne FK", "Eliteserien", "Noruega"],
  ["BSC Young Boys", "Super League", "Suíça"],
  ["Burgos CF", "La Liga 2", "Espanha"],
  ["Burnley", "Premier League", "Inglaterra"],
  ["Burton Albion", "League One", "Inglaterra"],
  ["CA Aldosivi", "Liga Profesional de Fútbol", "Argentina"],
  ["CA Banfield", "Liga Profesional de Fútbol", "Argentina"],
  ["CA Osasuna", "La Liga", "Espanha"],
  ["Cádiz CF", "La Liga 2", "Espanha"],
  ["Cagliari", "Serie A", "Itália"],
  ["Cambridge United", "League Two", "Inglaterra"],
  ["Carabobo FC", "Primera Division", "Venezuela"],
  ["Caracas FC", "Primera Division", "Venezuela"],
  ["Cardiff City", "League One", "Inglaterra"],
  ["Carrarese", "Serie B", "Itália"],
  ["Casa Pia", "Primeira Liga", "Portugal"],
  ["Catanzaro", "Serie B", "Itália"],
  ["Çaykur Rizespor", "Süper Lig", "Turquia"],
  ["CD Castellón", "La Liga 2", "Espanha"],
  ["CD Leganés", "La Liga 2", "Espanha"],
  ["CD Mirandés", "La Liga 2", "Espanha"],
  ["CD Nacional", "Primeira Liga", "Portugal"],
  ["CD Palestino", "Primera Division", "Chile"],
  ["CD Tondela", "Primeira Liga", "Portugal"],
  ["Celtic", "Premiership", "Escócia"],
  ["Central Coast Mariners", "A-League Men", "Austrália"],
  ["Central Cordoba SdE", "Liga Profesional de Fútbol", "Argentina"],
  ["Cercle Brugge KSV", "Pro League", "Bélgica"],
  ["Cerro Largo", "Primera División", "Uruguai"],
  ["Cerro Porteño", "División Profesional", "Paraguai"],
  ["Cesena FC", "Serie B", "Itália"],
  ["CF Montréal", "Major League Soccer", "Canadá"],
  ["CFR Cluj", "Liga I", "Roménia"],
  ["Changchun Yatai", "Super League", "Chile"],
  ["Charlotte FC", "Major League Soccer", "EUA"],
  ["Charlton Athletic", "Championship", "Inglaterra"],
  ["Chelsea", "Premier League", "Inglaterra"],
  ["Cheltenham Town", "League Two", "Inglaterra"],
  ["Chengdu Rongcheng", "Super League", "Chile"],
  ["Chennaiyin FC", "Super League", "Índia"],
  ["Chesterfield", "League Two", "Inglaterra"],
  ["Chicago Fire", "Major League Soccer", "EUA"],
  ["Cienciano", "Liga 1", "Peru"],
  ["Clermont Foot 63", "Ligue 2", "França"],
  ["Club Atlético San Martín", "Liga Profesional de Fútbol", "Argentina"],
  ["Club Atlético Sarmiento", "Liga Profesional de Fútbol", "Argentina"],
  ["Club Atlético Unión", "Liga Profesional de Fútbol", "Argentina"],
  ["Club Brugge KV", "Pro League", "Bélgica"],
  ["Club Nacional de Football", "Primera División", "Uruguai"],
  ["Club Olimpia", "División Profesional", "Paraguai"],
  ["Colchester United", "League Two", "Inglaterra"],
  ["Colo-Colo", "Primera Division", "Chile"],
  ["Colorado Rapids", "Major League Soccer", "EUA"],
  ["Columbus Crew", "Major League Soccer", "EUA"],
  ["Como", "Serie A", "Itália"],
  ["Córdoba CF", "La Liga 2", "Espanha"],
  ["Corinthians", "Série A", "Brasil"],
  ["Cork City", "Premier Division", "Irlanda"],
  ["Coventry City", "Championship", "Inglaterra"],
  ["Cracovia", "Ekstraklasa", "Polônia"],
  ["Crawley Town", "League Two", "Inglaterra"],
  ["Cremonese", "Serie A", "Itália"],
  ["Crewe Alexandra", "League Two", "Inglaterra"],
  ["Cruzeiro", "Série A", "Brasil"],
  ["Crystal Palace", "Premier League", "Inglaterra"],
  ["Csíkszereda Miercurea Ciuc", "Liga I", "Roménia"],
  ["Cultural Leonesa", "La Liga 2", "Espanha"],
  ["Daegu FC", "K League 1", "Coreia do Sul"],
  ["Daejeon Citizen", "K League 1", "Coreia do Sul"],
  ["Dalian Yingbo", "Super League", "Chile"],
  ["Damac FC", "Pro League", "Kuwait"],
  ["DC United", "Major League Soccer", "EUA"],
  ["Defensa y Justicia", "Liga Profesional de Fútbol", "Argentina"],
  ["Degerfors IF", "Allsvenskan", "Suécia"],
  ["Deportes Iquique", "Primera Division", "Chile"],
  ["Deportivo Alavés", "La Liga", "Espanha"],
  ["Deportivo Riestra", "Liga Profesional de Fútbol", "Argentina"],
  ["Deportivo Táchira", "Primera Division", "Venezuela"],
  ["Derby County", "Championship", "Inglaterra"],
  ["Derry City", "Premier Division", "Irlanda"],
  ["Dinamo Bucureşti", "Liga I", "Roménia"],
  ["Dinamo Zagreb", "Hrvatska nogometna liga", "Croácia"],
  ["Djurgårdens IF", "Allsvenskan", "Suécia"],
  ["Doncaster Rovers", "League One", "Inglaterra"],
  ["Drogheda United", "Premier Division", "Irlanda"],
  ["DSC Arminia Bielefeld", "2. Bundesliga", "Alemanha"],
  ["Dundee FC", "Premiership", "Escócia"],
  ["Dundee United FC", "Premiership", "Escócia"],
  ["Dynamo Dresden", "2. Bundesliga", "Alemanha"],
  ["Dynamo Kyiv", "Premier League", "Ucrânia"],
  ["East Bengal FC", "Super League", "Índia"],
  ["Eintracht Braunschweig", "2. Bundesliga", "Alemanha"],
  ["Eintracht Frankfurt", "Bundesliga", "Alemanha"],
  ["Elche CF", "La Liga", "Espanha"],
  ["Empoli", "Serie B", "Itália"],
  ["En Avant Guingamp", "Ligue 2", "França"],
  ["ESTAC Troyes", "Ligue 2", "França"],
  ["Estrela da Amadora", "Primeira Liga", "Portugal"],
  ["Estudiantes de La Plata", "Liga Profesional de Fútbol", "Argentina"],
  ["Everton", "Premier League", "Inglaterra"],
  ["Excelsior", "Eredivisie", "Holanda"],
  ["Exeter City", "League One", "Inglaterra"],
  ["Eyüpspor", "Süper Lig", "Turquia"],
  ["Falkirk", "Premiership", "Escócia"],
  ["Famalicão", "Primeira Liga", "Portugal"],
  ["Fatih Karagümrük", "Süper Lig", "Turquia"],
  ["FBC Melgar", "Liga 1", "Peru"],
  ["FC Andorra", "La Liga 2", "Espanha"],
  ["FC Annecy", "Ligue 2", "França"],
  ["FC Anyang", "K League 1", "Coreia do Sul"],
  ["FC Argeș", "Liga I", "Roménia"],
  ["FC Arouca", "Primeira Liga", "Portugal"],
  ["FC Augsburg", "Bundesliga", "Alemanha"],
  ["FC Barcelona", "La Liga", "Espanha"],
  ["FC Basel 1893", "Super League", "Suíça"],
  ["FC Bayern München", "Bundesliga", "Alemanha"],
  ["FC Botoşani", "Liga I", "Roménia"],
  ["FC Cincinnati", "Major League Soccer", "EUA"],
  ["FC Dallas", "Major League Soccer", "EUA"],
  ["FC Energie Cottbus", "3. Liga", "Alemanha"],
  ["FC Erzgebirge Aue", "3. Liga", "Alemanha"],
  ["FC Goa", "Super League", "Índia"],
  ["FC Groningen", "Eredivisie", "Holanda"],
  ["FC Hansa Rostock", "3. Liga", "Alemanha"],
  ["FC Hermannstadt", "Liga I", "Roménia"],
  ["FC Ingolstadt 04", "3. Liga", "Alemanha"],
  ["FC København", "Superliga", "Dinamarca"],
  ["FC Lausanne-Sport", "Super League", "Suíça"],
  ["FC Lorient", "Ligue 1", "França"],
  ["FC Lugano", "Super League", "Suíça"],
  ["FC Luzern", "Super League", "Suíça"],
  ["FC Metz", "Ligue 1", "França"],
  ["FC Midtjylland", "Superliga", "Dinamarca"],
  ["FC Nantes", "Ligue 1", "França"],
  ["FC Nordsjælland", "Superliga", "Dinamarca"],
  ["FC Porto", "Primeira Liga", "Portugal"],
  ["FC Red Bull Salzburg", "Bundesliga", "Alemanha"],
  ["FC Schalke 04", "2. Bundesliga", "Alemanha"],
  ["FC Seoul", "K League 1", "Coreia do Sul"],
  ["FC Sion", "Super League", "Suíça"],
  ["FC St. Pauli", "Bundesliga", "Alemanha"],
  ["FC St.Gallen 1879", "Super League", "Suíça"],
  ["FC Thun", "Super League", "Suíça"],
  ["FC Twente", "Eredivisie", "Holanda"],
  ["FC Utrecht", "Eredivisie", "Holanda"],
  ["FC Volendam", "Eredivisie", "Holanda"],
  ["FC Winterthur", "Super League", "Suíça"],
  ["FC Zürich", "Super League", "Suíça"],
  ["FCSB", "Liga I", "Roménia"],
  ["FCV Dender EH", "Pro League", "Bélgica"],
  ["FCV Farul Constanța", "Liga I", "Roménia"],
  ["Fenerbahçe SK", "Süper Lig", "Turquia"],
  ["Ferencvárosi Torna Club", "Nemzeti Bajnokság I", "Hungria"],
  ["Feyenoord", "Eredivisie", "Holanda"],
  ["Fiorentina", "Serie A", "Itália"],
  ["FK Austria Wien", "Bundesliga", "Alemanha"],
  ["FK Bodø/Glimt", "Eliteserien", "Noruega"],
  ["FK Haugesund", "Eliteserien", "Noruega"],
  ["Flamengo", "Série A", "Brasil"],
  ["Fleetwood Town", "League Two", "Inglaterra"],
  ["Fluminense", "Série A", "Brasil"],
  ["Fortaleza", "Série A", "Brasil"],
  ["Fortuna Düsseldorf", "2. Bundesliga", "Alemanha"],
  ["Fortuna Sittard", "Eredivisie", "Holanda"],
  ["Fredericia", "Superliga", "Dinamarca"],
  ["Fredrikstad FK", "Eliteserien", "Noruega"],
  ["Frosinone", "Serie B", "Itália"],
  ["Fulham FC", "Premier League", "Inglaterra"],
  ["GAIS", "Allsvenskan", "Suécia"],
  ["Galatasaray SK", "Süper Lig", "Turquia"],
  ["Galway United", "Premier Division", "Irlanda"],
  ["Gangwon FC", "K League 1", "Coreia do Sul"],
  ["Gaziantep FK", "Süper Lig", "Turquia"],
  ["GD Estoril Praia", "Primeira Liga", "Portugal"],
  ["Gençlerbirliği SK", "Süper Lig", "Turquia"],
  ["Genoa", "Serie A", "Itália"],
  ["Getafe CF", "La Liga", "Espanha"],
  ["Gil Vicente FC", "Primeira Liga", "Portugal"],
  ["Gillingham", "League Two", "Inglaterra"],
  ["Gimcheon Sangmu FC", "K League 1", "Coreia do Sul"],
  ["Gimnasia y Esgrima La Plata", "Liga Profesional de Fútbol", "Argentina"],
  ["Girona FC", "La Liga", "Espanha"],
  ["GKS Katowice", "Ekstraklasa", "Polônia"],
  ["Go Ahead Eagles", "Eredivisie", "Holanda"],
  ["Godoy Cruz", "Liga Profesional de Fútbol", "Argentina"],
  ["Górnik Zabrze", "Ekstraklasa", "Polônia"],
  ["Göztepe SK", "Süper Lig", "Turquia"],
  ["Granada CF", "La Liga 2", "Espanha"],
  ["Grasshopper Club Zürich", "Super League", "Suíça"],
  ["Grazer AK 1902", "Bundesliga", "Alemanha"],
  ["Grêmio", "Série A", "Brasil"],
  ["Grenoble Foot 38", "Ligue 2", "França"],
  ["Grimsby Town", "League Two", "Inglaterra"],
  ["Gualberto Villarroel SJ", "División de Fútbol Profesional", "Bolívia"],
  ["Guaraní", "División Profesional", "Paraguai"],
  ["Gwangju FC", "K League 1", "Coreia do Sul"],
  ["Hajduk Split", "Hrvatska nogometna liga", "Croácia"],
  ["Halmstads BK", "Allsvenskan", "Suécia"],
  ["Hamarkameratene", "Eliteserien", "Noruega"],
  ["Hamburger SV", "Bundesliga", "Alemanha"],
  ["Hammarby Fotboll", "Allsvenskan", "Suécia"],
  ["Hannover 96", "2. Bundesliga", "Alemanha"],
  ["Harrogate Town", "League Two", "Inglaterra"],
  ["Hearts", "Premiership", "Escócia"],
  ["Hellas Verona FC", "Serie A", "Itália"],
  ["Henan FC", "Super League", "Índia"],
  ["Heracles Almelo", "Eredivisie", "Holanda"],
  ["Hertha BSC", "2. Bundesliga", "Alemanha"],
  ["Hibernian", "Premiership", "Escócia"],
  ["HJK Helsinki", "Veikkausliiga", "Finlândia"],
  ["Holstein Kiel", "2. Bundesliga", "Alemanha"],
  ["Houston Dynamo", "Major League Soccer", "EUA"],
  ["Huddersfield Town", "League One", "Inglaterra"],
  ["Hull City", "Championship", "Inglaterra"],
  ["Huracán", "Liga Profesional de Fútbol", "Argentina"],
  ["Hyderabad FC", "Super League", "Índia"],
  ["IF Brommapojkarna", "Allsvenskan", "Suécia"],
  ["IF Elfsborg", "Allsvenskan", "Suécia"],
  ["IFK Göteborg", "Allsvenskan", "Suécia"],
  ["IFK Norrköping", "Allsvenskan", "Suécia"],
  ["IFK Värnamo", "Allsvenskan", "Suécia"],
  ["IK Sirius", "Allsvenskan", "Suécia"],
  ["Independiente", "Liga Profesional de Fútbol", "Argentina"],
  ["Independiente del Valle", "Serie A", "Brasil"],
  ["Independiente Rivadavia", "Liga Profesional de Fútbol", "Argentina"],
  ["Instituto Atlético Central Córdoba", "Liga Profesional de Fútbol", "Argentina"],
  ["Inter", "Serie A", "Itália"],
  ["Inter Miami", "Major League Soccer", "EUA"],
  ["Internacional", "Série A", "Brasil"],
  ["Ipswich Town", "Championship", "Inglaterra"],
  ["Jagiellonia Białystok", "Ekstraklasa", "Polônia"],
  ["Jamshedpur FC", "Super League", "Índia"],
  ["Jeju United FC", "K League 1", "Coreia do Sul"],
  ["Jeonbuk Hyundai Motors", "K League 1", "Coreia do Sul"],
  ["Juventus", "Serie A", "Itália"],
  ["KAA Gent", "Pro League", "Bélgica"],
  ["Karlsruher SC", "2. Bundesliga", "Alemanha"],
  ["Kasımpaşa SK", "Süper Lig", "Turquia"],
  ["Kayserispor", "Süper Lig", "Turquia"],
  ["Kerala Blasters FC", "Super League", "Índia"],
  ["KFUM-Kameratene Oslo", "Eliteserien", "Noruega"],
  ["Kilmarnock", "Premiership", "Escócia"],
  ["Kocaelispor", "Süper Lig", "Turquia"],
  ["Konyaspor", "Süper Lig", "Turquia"],
  ["Korona Kielce", "Ekstraklasa", "Polônia"],
  ["KRC Genk", "Pro League", "Bélgica"],
  ["Kristiansund BK", "Eliteserien", "Noruega"],
  ["KV Mechelen", "Pro League", "Bélgica"],
  ["KVC Westerlo", "Pro League", "Bélgica"],
  ["LA Galaxy", "Major League Soccer", "EUA"],
  ["Lanús", "Liga Profesional de Fútbol", "Argentina"],
  ["LASK Linz", "Bundesliga", "Alemanha"],
  ["Lazio", "Serie A", "Itália"],
  ["LDU Quito", "Serie A", "Ecuador"],
  ["Le Havre AC", "Ligue 1", "França"],
  ["Le Mans FC", "Ligue 2", "França"],
  ["Lecce", "Serie A", "Itália"],
  ["Lech Poznań", "Ekstraklasa", "Polônia"],
  ["Lechia Gdańsk", "Ekstraklasa", "Polônia"],
  ["Leeds United", "Premier League", "Inglaterra"],
  ["Legia Warszawa", "Ekstraklasa", "Polônia"],
  ["Leicester City", "Championship", "Inglaterra"],
  ["Levante UD", "La Liga", "Espanha"],
  ["Leyton Orient", "League One", "Inglaterra"],
  ["Libertad", "División Profesional", "Paraguai"],
  ["Lille OSC", "Ligue 1", "França"],
  ["Lincoln City", "League One", "Inglaterra"],
  ["Liverpool", "Premier League", "Inglaterra"],
  ["Livingston FC", "Premiership", "Escócia"],
  ["Los Angeles FC", "Major League Soccer", "EUA"],
  ["Luton Town", "League One", "Inglaterra"],
  ["Macarthur FC", "A-League Men", "Austrália"],
  ["Málaga CF", "La Liga 2", "Espanha"],
  ["Malmö FF", "Allsvenskan", "Suécia"],
  ["Manchester City", "Premier League", "Inglaterra"],
  ["Manchester United", "Premier League", "Inglaterra"],
  ["Mansfield Town", "League One", "Inglaterra"],
  ["Mantova", "Serie B", "Itália"],
  ["Medipol Başakşehir FK", "Süper Lig", "Turquia"],
  ["Meizhou Hakka", "Super League", "Índia"],
  ["Melbourne City FC", "A-League Men", "Austrália"],
  ["Melbourne Victory", "A-League Men", "Austrália"],
  ["Metaloglobus București", "Liga I", "Roménia"],
  ["Middlesbrough", "Championship", "Inglaterra"],
  ["Millwall FC", "Championship", "Inglaterra"],
  ["Milton Keynes Dons", "League Two", "Inglaterra"],
  ["Minnesota United FC", "Major League Soccer", "EUA"],
  ["Mjällby AIF", "Allsvenskan", "Suécia"],
  ["Modena", "Serie B", "Itália"],
  ["Mohammedan SC", "Super League", "Índia"],
  ["Mohun Bagan Super Giant", "Super League", "Índia"],
  ["Molde FK", "Eliteserien", "Noruega"],
  ["Montpellier HSC", "Ligue 2", "França"],
  ["Monza", "Serie B", "Itália"],
  ["Moreirense FC", "Primeira Liga", "Portugal"],
  ["Motherwell FC", "Premiership", "Escócia"],
  ["Motor Lublin", "Ekstraklasa", "Polônia"],
  ["MSV Duisburg", "3. Liga", "Alemanha"],
  ["Mumbai City FC", "Super League", "Índia"],
  ["Mushuc Runa", "Serie A", "Ecuador"],
  ["NAC Breda", "Eredivisie", "Holanda"],
  ["Nacional Potosí", "División de Fútbol Profesional", "Bolívia"],
  ["Napoli", "Serie A", "Itália"],
  ["Nashville SC", "Major League Soccer", "EUA"],
  ["NEC Nijmegen", "Eredivisie", "Holanda"],
  ["NEOM SC", "Pro League", "Bélgica"],
  ["New England Revolution", "Major League Soccer", "EUA"],
  ["New York City FC", "Major League Soccer", "EUA"],
  ["New York Red Bulls", "Major League Soccer", "EUA"],
  ["Newcastle Jets", "A-League Men", "Austrália"],
  ["Newcastle United", "Premier League", "Inglaterra"],
  ["Newell's Old Boys", "Liga Profesional de Fútbol", "Argentina"],
  ["Newport County", "League Two", "Inglaterra"],
  ["Northampton Town", "League One", "Inglaterra"],
  ["NorthEast United", "Super League", "Índia"],
  ["Norwich City", "Championship", "Inglaterra"],
  ["Nottingham Forest", "Premier League", "Inglaterra"],
  ["Notts County", "League Two", "Inglaterra"],
  ["Odense Boldklub", "Superliga", "Dinamarca"],
  ["Odisha FC", "Super League", "Índia"],
  ["OGC Nice", "Ligue 1", "França"],
  ["Oldham Athletic", "League Two", "Inglaterra"],
  ["Olympiacos FC", "Super League", "Grécia"],
  ["Olympique de Marseille", "Ligue 1", "França"],
  ["Olympique Lyonnais", "Ligue 1", "França"],
  ["Once Caldas", "Categoría Primera A", "Colômbia"],
  ["Orlando City SC", "Major League Soccer", "EUA"],
  ["Östers IF", "Allsvenskan", "Suécia"],
  ["Oțelul Galați", "Liga I", "Roménia"],
  ["Oud-Heverlee Leuven", "Pro League", "Bélgica"],
  ["Oxford United", "Championship", "Inglaterra"],
  ["Padova", "Serie B", "Itália"],
  ["Palermo FC", "Serie B", "Itália"],
  ["Palmeiras", "Série A", "Brasil"],
  ["Panathinaikos FC", "Super League", "Grécia"],
  ["PAOK", "Super League", "Grécia"],
  ["Paris FC", "Ligue 1", "França"],
  ["Paris Saint-Germain", "Ligue 1", "França"],
  ["Parma", "Serie A", "Itália"],
  ["Pau FC", "Ligue 2", "França"],
  ["PEC Zwolle", "Eredivisie", "Holanda"],
  ["Peñarol", "Primera División", "Uruguai"],
  ["Perth Glory", "A-League Men", "Austrália"],
  ["Pescara", "Serie B", "Itália"],
  ["Peterborough United", "League One", "Inglaterra"],
  ["Philadelphia Union", "Major League Soccer", "EUA"],
  ["Piast Gliwice", "Ekstraklasa", "Polônia"],
  ["Pisa", "Serie A", "Itália"],
  ["Platense", "Liga Profesional de Fútbol", "Argentina"],
  ["Plymouth Argyle", "League One", "Inglaterra"],
  ["Pogoń Szczecin", "Ekstraklasa", "Polônia"],
  ["Pohang Steelers", "K League 1", "Coreia do Sul"],
  ["Port Vale", "League One", "Inglaterra"],
  ["Portland Timbers", "Major League Soccer", "EUA"],
  ["Portsmouth", "Championship", "Inglaterra"],
  ["Preston North End", "Championship", "Inglaterra"],
  ["PSV", "Eredivisie", "Holanda"],
  ["Punjab FC", "Super League", "Índia"],
  ["Qarabağ FK", "Premyer Liqa", "Azerbaijão"],
  ["Qingdao Hainiu FC", "Super League", "China"],
  ["Qingdao West Coast FC", "Super League", "China"],
  ["Queens Park Rangers", "Championship", "Inglaterra"],
  ["RAAL La Louvière", "Pro League", "Bélgica"],
  ["Racing Club", "Liga Profesional de Fútbol", "Argentina"],
  ["Racing Club de Montevideo", "Primera División", "Uruguai"],
  ["Racing Santander", "La Liga 2", "Espanha"],
  ["Radomiak Radom", "Ekstraklasa", "Polônia"],
  ["Raków Częstochowa", "Ekstraklasa", "Polônia"],
  ["Randers FC", "Superliga", "Dinamarca"],
  ["Rangers FC", "Premiership", "Escócia"],
  ["Rapid Bucuresti", "Liga I", "Roménia"],
  ["Rayo Vallecano", "La Liga", "Espanha"],
  ["RB Leipzig", "Bundesliga", "Alemanha"],
  ["RC Celta", "La Liga", "Espanha"],
  ["RC Deportivo de La Coruña", "La Liga 2", "Espanha"],
  ["RC Lens", "Ligue 1", "França"],
  ["RC Strasbourg Alsace", "Ligue 1", "França"],
  ["RCD Espanyol", "La Liga", "Espanha"],
  ["RCD Mallorca", "La Liga", "Espanha"],
  ["Reading FC", "League One", "Inglaterra"],
  ["Real Betis Balompié", "La Liga", "Espanha"],
  ["Real Madrid", "La Liga", "Espanha"],
  ["Real Oviedo", "La Liga", "Espanha"],
  ["Real Salt Lake", "Major League Soccer", "EUA"],
  ["Real Sociedad", "La Liga", "Espanha"],
  ["Real Sociedad de Fútbol B", "La Liga 2", "Espanha"],
  ["Real Sporting de Gijón", "La Liga 2", "Espanha"],
  ["Real Valladolid CF", "La Liga 2", "Espanha"],
  ["Real Zaragoza", "La Liga 2", "Espanha"],
  ["Red Star FC", "Ligue 2", "França"],
  ["Reggiana", "Serie B", "Itália"],
  ["Rio Ave FC", "Primeira Liga", "Portugal"],
  ["River Plate", "Liga Profesional de Fútbol", "Argentina"],
  ["Rodez Aveyron Football", "Ligue 2", "França"],
  ["Roma", "Serie A", "Itália"],
  ["Rosario Central", "Liga Profesional de Fútbol", "Argentina"],
  ["Rosenborg BK", "Eliteserien", "Noruega"],
  ["Rot-Weiss Essen", "3. Liga", "Alemanha"],
  ["Rotherham United", "League One", "Inglaterra"],
  ["Royal Antwerp FC", "Pro League", "Bélgica"],
  ["Royal Charleroi Sporting Club", "Pro League", "Bélgica"],
  ["RSC Anderlecht", "Pro League", "Bélgica"],
  ["Salford City", "League Two", "Inglaterra"],
  ["Sampdoria", "Serie B", "Itália"],
  ["Samsunspor", "Süper Lig", "Turquia"],
  ["San Antonio Bulo Bulo", "División de Fútbol Profesional", "Colômbia"],
  ["San Diego FC", "Major League Soccer", "EUA"],
  ["San Jose Earthquakes", "Major League Soccer", "EUA"],
  ["San Lorenzo de Almagro", "Liga Profesional de Fútbol", "Argentina"],
  ["Sandefjord Fotball", "Eliteserien", "Noruega"],
  ["Santa Clara", "Primeira Liga", "Portugal"],
  ["São Paulo", "Série A", "Brasil"],
  ["Sarpsborg 08 FF", "Eliteserien", "Noruega"],
  ["Sassuolo", "Serie A", "Itália"],
  ["SC Freiburg", "Bundesliga", "Alemanha"],
  ["SC Heerenveen", "Eredivisie", "Holanda"],
  ["SC Paderborn 07", "2. Bundesliga", "Alemanha"],
  ["SC Preußen Münster", "2. Bundesliga", "Alemanha"],
  ["SC Rheindorf Altach", "Bundesliga", "Alemanha"],
  ["SC Verl", "3. Liga", "Alemanha"],
  ["SD Eibar", "La Liga 2", "Espanha"],
  ["SD Huesca", "La Liga 2", "Espanha"],
  ["Seattle Sounders FC", "Major League Soccer", "EUA"],
  ["Servette FC", "Super League", "Suécia"],
  ["Sevilla FC", "La Liga", "Espanha"],
  ["Shakhtar Donetsk", "Premier League", "Ucrânia"],
  ["Shamrock Rovers", "Premier Division", "Irlanda"],
  ["Shandong Taishan", "Super League", "China"],
  ["Shanghai Port", "Super League", "China"],
  ["Shanghai Shenhua", "Super League", "China"],
  ["Sheffield United", "Championship", "Inglaterra"],
  ["Sheffield Wednesday", "Championship", "Inglaterra"],
  ["Shelbourne FC", "Premier Division", "Irlanda"],
  ["Shenzhen Peng City", "Super League", "China"],
  ["Shrewsbury Town", "League Two", "Inglaterra"],
  ["Silkeborg IF", "Superliga", "Dinamarca"],
  ["Sint-Truidense VV", "Pro League", "Bélgica"],
  ["SK Brann", "Eliteserien", "Noruega"],
  ["SK Rapid", "Bundesliga", "Alemanha"],
  ["SK Slavia Praha", "První liga", "República Tcheca"],
  ["SK Sturm Graz", "Bundesliga", "Alemanha"],
  ["SL Benfica", "Primeira Liga", "Portugal"],
  ["Sligo Rovers", "Premier Division", "Irlanda"],
  ["Sønderjyske Fodbold", "Superliga", "Dinamarca"],
  ["Southampton", "Championship", "Inglaterra"],
  ["Sparta Praha", "První liga", "República Tcheca"],
  ["Sparta Rotterdam", "Eredivisie", "Holanda"],
  ["Spezia", "Serie B", "Itália"],
  ["Sporting Club Bastia", "Ligue 2", "França"],
  ["Sporting Clube de Braga", "Primeira Liga", "Portugal"],
  ["Sporting CP", "Primeira Liga", "Portugal"],
  ["Sporting Cristal", "Liga 1", "Peru"],
  ["Sporting Kansas City", "Major League Soccer", "EUA"],
  ["Sportivo Luqueño", "División Profesional", "Paraguai"],
  ["SpVgg Greuther Fürth", "2. Bundesliga", "Alemanha"],
  ["SS Juve Stabia", "Serie B", "Itália"],
  ["SSC Bari", "Serie B", "Itália"],
  ["SSV Jahn Regensburg", "3. Liga", "Alemanha"],
  ["SSV Ulm 1846", "3. Liga", "Alemanha"],
  ["St Patrick's Athletic FC", "Premier Division", "Irlanda"],
  ["St. Louis CITY SC", "Major League Soccer", "EUA"],
  ["St. Mirren", "Premiership", "Escócia"],
  ["Stade Brestois 29", "Ligue 1", "França"],
  ["Stade de Reims", "Ligue 2", "França"],
  ["Stade Lavallois Mayenne FC", "Ligue 2", "França"],
  ["Stade Rennais FC", "Ligue 1", "França"],
  ["Standard de Liège", "Pro League", "Bélgica"],
  ["Stevenage", "League One", "Inglaterra"],
  ["Stockport County", "League One", "Inglaterra"],
  ["Stoke City", "Championship", "Inglaterra"],
  ["Strømsgodset IF", "Eliteserien", "Noruega"],
  ["Südtirol", "Serie B", "Itália"],
  ["Sunderland", "Premier League", "Inglaterra"],
  ["Suwon FC", "K League 1", "Coreia do Sul"],
  ["SV Darmstadt 98", "2. Bundesliga", "Alemanha"],
  ["SV Elversberg", "2. Bundesliga", "Alemanha"],
  ["SV Ried", "Bundesliga", "Alemanha"],
  ["SV Waldhof Mannheim", "3. Liga", "Alemanha"],
  ["SV Wehen Wiesbaden", "3. Liga", "Alemanha"],
  ["SV Werder Bremen", "Bundesliga", "Alemanha"],
  ["SV Zulte Waregem", "Pro League", "Bélgica"],
  ["Swansea City", "Championship", "Gales"],
  ["Swindon Town", "League Two", "Inglaterra"],
  ["Sydney FC", "A-League Men", "Austrália"],
  ["Talleres", "Liga Profesional de Fútbol", "Argentina"],
  ["Telstar", "Eredivisie", "Holanda"],
  ["Tianjin Jinmen Tiger", "Super League", "China"],
  ["Tigre", "Liga Profesional de Fútbol", "Argentina"],
  ["Torino", "Serie A", "Itália"],
  ["Toronto FC", "Major League Soccer", "EUA"],
  ["Tottenham Hotspur", "Premier League", "Inglaterra"],
  ["Toulouse FC", "Ligue 1", "França"],
  ["Trabzonspor", "Süper Lig", "Turquia"],
  ["Tranmere Rovers", "League Two", "Inglaterra"],
  ["Tromsø IL", "Eliteserien", "Noruega"],
  ["TSG 1899 Hoffenheim", "Bundesliga", "Alemanha"],
  ["TSG 1899 Hoffenheim II", "3. Liga", "Alemanha"],
  ["TSV 1860 München", "3. Liga", "Alemanha"],
  ["TSV Hartberg", "Bundesliga", "Alemanha"],
  ["TSV Havelse", "3. Liga", "Alemanha"],
  ["UD Almería", "La Liga 2", "Espanha"],
  ["UD Las Palmas", "La Liga 2", "Espanha"],
  ["Udinese", "Serie A", "Itália"],
  ["Ulsan HD FC", "K League 1", "Coreia do Sul"],
  ["Unión Española", "Primera Division", "Espanha"],
  ["Union Saint-Gilloise", "Pro League", "Bélgica"],
  ["Unirea Slobozia", "Liga I", "Roménia"],
  ["United Tigers SC", "Super League", "China"],
  ["Universidad Católica", "Primera Division", "Chile"],
  ["Universidad Católica del Ecuador", "Serie A", "Ecuador"],
  ["Universidad de Chile", "Primera Division", "Chile"],
  ["Universitario de Deportes", "Liga 1", "Peru"],
  ["Universitatea Cluj", "Liga I", "Roménia"],
  ["Universitatea Craiova", "Liga I", "Roménia"],
  ["US Boulogne Cote d'Opale", "Ligue 2", "França"],
  ["USL Dunkerque", "Ligue 2", "França"],
  ["UTA Arad", "Liga I", "Roménia"],
  ["Valencia CF", "La Liga", "Espanha"],
  ["Vålerenga Fotball", "Eliteserien", "Noruega"],
  ["Vancouver Whitecaps FC", "Major League Soccer", "EUA"],
  ["Vasco da Gama", "Série A", "Brasil"],
  ["Vejle Boldklub", "Superliga", "Dinamarca"],
  ["Vélez Sarsfield", "Liga Profesional de Fútbol", "Argentina"],
  ["Venezia", "Serie B", "Itália"],
  ["VfB Stuttgart", "Bundesliga", "Alemanha"],
  ["VfB Stuttgart II", "3. Liga", "Alemanha"],
  ["VfL Bochum 1848", "2. Bundesliga", "Alemanha"],
  ["VfL Osnabrück", "3. Liga", "Alemanha"],
  ["VfL Wolfsburg", "Bundesliga", "Alemanha"],
  ["Viborg FF", "Superliga", "Dinamarca"],
  ["Viking FK", "Eliteserien", "Noruega"],
  ["Viktoria Köln", "3. Liga", "Alemanha"],
  ["Viktoria Plzeň", "První liga", "República Tcheca"],
  ["Villarreal CF", "La Liga", "Espanha"],
  ["Virtus Entella", "Serie B", "Itália"],
  ["Vitória", "Série A", "Brasil"],
  ["Vitória SC", "Primeira Liga", "Portugal"],
  ["Walsall", "League Two", "Inglaterra"],
  ["Waterford FC", "Premier Division", "Irlanda"],
  ["Watford", "Championship", "Inglaterra"],
  ["Wellington Phoenix", "A-League Men", "Austrália"],
  ["West Bromwich Albion", "Championship", "Inglaterra"],
  ["West Ham United", "Premier League", "Inglaterra"],
  ["Western Sydney Wanderers", "A-League Men", "Austrália"],
  ["Western United", "A-League Men", "Austrália"],
  ["Widzew Łódź", "Ekstraklasa", "Polônia"],
  ["Wigan Athletic", "League One", "Inglaterra"],
  ["Wisła Płock", "Ekstraklasa", "Polônia"],
  ["Wolfsberger AC", "Bundesliga", "Alemanha"],
  ["Wolverhampton Wanderers", "Premier League", "Inglaterra"],
  ["Wrexham", "Championship", "Inglaterra"],
  ["WSG Tirol", "Bundesliga", "Alemanha"],
  ["Wuhan Three Towns", "Super League", "China"],
  ["Wycombe Wanderers", "League One", "Inglaterra"],
  ["Yunnan Yukun", "Super League", "China"],
  ["Zagłębie Lubin", "Ekstraklasa", "Polônia"],
  ["Zhejiang FC", "Super League", "China"],
];
