-- FC Arena: Supabase/PostgreSQL foundation
-- Apply this migration in Supabase SQL Editor.

create extension if not exists pgcrypto;

create type public.user_role as enum ('admin', 'player', 'viewer');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role public.user_role not null default 'viewer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.players (
  id bigint generated by default as identity primary key,
  user_id uuid unique references public.profiles(id) on delete set null,
  name text not null,
  nickname text not null unique,
  avatar text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  league text not null,
  country text not null
);

create table public.championships (
  id bigint generated by default as identity primary key,
  name text not null,
  format text not null check (format in ('league', 'knockout', 'groups_knockout')),
  starts_at timestamptz not null,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.matches (
  id bigint generated by default as identity primary key,
  player1_id bigint not null references public.players(id) on delete restrict,
  player2_id bigint not null references public.players(id) on delete restrict,
  team1_id bigint not null references public.teams(id) on delete restrict,
  team2_id bigint not null references public.teams(id) on delete restrict,
  score1 integer not null default 0 check (score1 >= 0),
  score2 integer not null default 0 check (score2 >= 0),
  championship_id bigint references public.championships(id) on delete set null,
  played_at timestamptz not null default now(),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (player1_id <> player2_id),
  check (team1_id <> team2_id)
);

create table public.fixtures (
  id bigint generated by default as identity primary key,
  championship_id bigint not null references public.championships(id) on delete cascade,
  round_number integer not null,
  stage text not null default 'league',
  player1_id bigint not null references public.players(id) on delete restrict,
  player2_id bigint not null references public.players(id) on delete restrict,
  match_id bigint unique references public.matches(id) on delete set null,
  created_at timestamptz not null default now(),
  check (player1_id <> player2_id),
  unique (championship_id, player1_id, player2_id)
);

create index matches_played_at_idx on public.matches (played_at desc);
create index matches_player_pair_idx on public.matches (player1_id, player2_id);
create index matches_championship_idx on public.matches (championship_id);
create index fixtures_championship_round_idx on public.fixtures (championship_id, round_number, id);
create index players_user_id_idx on public.players (user_id);

-- Keep updated_at consistent for records changed through Postgres.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger players_set_updated_at
before update on public.players
for each row execute function public.set_updated_at();

create trigger championships_set_updated_at
before update on public.championships
for each row execute function public.set_updated_at();

create trigger matches_set_updated_at
before update on public.matches
for each row execute function public.set_updated_at();

-- Automatically create a viewer profile for every new Auth user.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, role)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(coalesce(new.email, 'Usuário'), '@', 1)),
    'viewer'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Role helper. It reads profiles without exposing a writable role field to clients.
create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

revoke all on function public.current_user_role() from public;
grant execute on function public.current_user_role() to authenticated;

-- Bootstrap helper for the first administrator. Execute manually after creating
-- the first Auth account, replacing the UUID below with that user's id.
-- update public.profiles set role = 'admin' where id = 'YOUR-FIRST-USER-UUID';

alter table public.profiles enable row level security;
alter table public.players enable row level security;
alter table public.teams enable row level security;
alter table public.championships enable row level security;
alter table public.matches enable row level security;
alter table public.fixtures enable row level security;

-- Profiles: authenticated users can read their own profile. Admins can read all.
create policy profiles_select_own_or_admin on public.profiles
for select to authenticated
using (id = auth.uid() or public.current_user_role() = 'admin');

create policy profiles_update_own_or_admin on public.profiles
for update to authenticated
using (id = auth.uid() or public.current_user_role() = 'admin')
with check (id = auth.uid() or public.current_user_role() = 'admin');

-- Players: everyone authenticated can read. A player can update only their
-- own linked player row; admins can manage all player rows.
create policy players_select_authenticated on public.players
for select to authenticated using (true);

create policy players_insert_admin on public.players
for insert to authenticated
with check (public.current_user_role() = 'admin');

create policy players_update_own_or_admin on public.players
for update to authenticated
using (public.current_user_role() = 'admin' or user_id = auth.uid())
with check (public.current_user_role() = 'admin' or user_id = auth.uid());

create policy players_delete_admin on public.players
for delete to authenticated
using (public.current_user_role() = 'admin');

-- Teams are read-only for non-admin users.
create policy teams_select_authenticated on public.teams
for select to authenticated using (true);

create policy teams_insert_admin on public.teams
for insert to authenticated
with check (public.current_user_role() = 'admin');

create policy teams_update_admin on public.teams
for update to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy teams_delete_admin on public.teams
for delete to authenticated
using (public.current_user_role() = 'admin');

-- Championships: all authenticated users can view; admin manages.
create policy championships_select_authenticated on public.championships
for select to authenticated using (true);

create policy championships_insert_admin on public.championships
for insert to authenticated
with check (public.current_user_role() = 'admin');

create policy championships_update_admin on public.championships
for update to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy championships_delete_admin on public.championships
for delete to authenticated
using (public.current_user_role() = 'admin');

-- Fixtures are generated/changed by privileged application operations.
create policy fixtures_select_authenticated on public.fixtures
for select to authenticated using (true);

create policy fixtures_insert_admin on public.fixtures
for insert to authenticated
with check (public.current_user_role() = 'admin');

create policy fixtures_update_admin on public.fixtures
for update to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy fixtures_delete_admin on public.fixtures
for delete to authenticated
using (public.current_user_role() = 'admin');

-- Matches: everyone authenticated can read. Admin can do everything.
-- A player may INSERT a result only if the match belongs to that player.
-- Once inserted, that player cannot UPDATE it: corrections belong to admins.
create policy matches_select_authenticated on public.matches
for select to authenticated using (true);

create policy matches_insert_admin_or_own_player on public.matches
for insert to authenticated
with check (
  public.current_user_role() = 'admin'
  or exists (
    select 1 from public.players p
    where p.user_id = auth.uid()
      and (p.id = player1_id or p.id = player2_id)
  )
);

create policy matches_update_admin on public.matches
for update to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy matches_delete_admin on public.matches
for delete to authenticated
using (public.current_user_role() = 'admin');

-- Realtime publication for live result updates and structural changes.
alter publication supabase_realtime add table public.matches;
alter publication supabase_realtime add table public.fixtures;
alter publication supabase_realtime add table public.championships;
alter publication supabase_realtime add table public.players;

-- Required grants for the client role.
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.profiles, public.players, public.teams,
  public.championships, public.matches, public.fixtures to authenticated;
grant usage, select on all sequences in schema public to authenticated;
